autoInstallPeers: true
nodeLinker: hoisted

allowBuilds:
  esbuild: true

minimumReleaseAgeExclude:
  - '@deepseek-ai/cordis@4.0.1'
  - '@deepseek-ai/dsh-settings@0.1.0-rc.6'
  - '@deepseek-ai/schemastery@3.18.1'
